# Copyright (c) 2024 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
name: Release Go Client Libraries

on:
  workflow_call:
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Get Latest Release Version
        id: get_release
        run: |
          REPO="${{ github.repository }}"
          echo "Fetching latest release for $REPO"
          RELEASE_VERSION=$(curl -s "https://api.github.com/repos/$REPO/releases/latest" | jq -r '.tag_name')
          if [[ "$RELEASE_VERSION" == "null" ]]; then
            echo "No release found for $REPO"
            RELEASE_VERSION="v0.0.0"
          fi
          echo "Latest release version: $RELEASE_VERSION"
          echo "::set-output name=release_version::$RELEASE_VERSION"

      - name: Calculate Next Minor Version
        id: calculate_version
        run: |
          RELEASE_VERSION="${{ steps.get_release.outputs.release_version }}"
          VERSION="${RELEASE_VERSION#v}"
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          NEXT_MINOR=$((MINOR + 1))
          NEW_VERSION="v$MAJOR.$NEXT_MINOR.0"
          echo "Next version: $NEW_VERSION"
          echo "::set-output name=new_version::$NEW_VERSION"

      - name: Output Version
        run: echo "Determined version:${{ steps.calculate_version.outputs.new_version }}"
