# Copyright (c) 2024 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

# This workflow is used to release libraries like gobrick, gofsutil etc.
name: Release Go Client Libraries

on:
  workflow_call:
    inputs:
      version:
        description: 'Version to release (major.minor.patch), e.g., 1.0.0'
        required: true

jobs:
  compute-version:
    runs-on: ubuntu-latest

    outputs:
      next_version: ${{ steps.increment_version.outputs.next_version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Current Version (Latest Tag)
        id: determine_version
        run: |
          CURRENT_VERSION=$(git describe --tags --abbrev=0 || echo "0.0.0")
          if [[ ! "$CURRENT_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format: $CURRENT_VERSION"
            exit 1
          fi
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Increment Major Version
        id: increment_version
        run: |
          IFS='.' read -r -a VERSION_PARTS <<< "${{ env.CURRENT_VERSION }}"
          NEXT_MAJOR_VERSION=$((VERSION_PARTS[0] + 1))
          NEXT_VERSION="${NEXT_MAJOR_VERSION}.0.0"
          echo "::set-output name=next_version::$NEXT_VERSION"

  build-and-scan:
    name: Build, Scan, and Release
    runs-on: ubuntu-latest
    steps:
      - name: Validate version input
        run: |
          VERSION=${{ needs.compute-version.outputs.next_version }}
          if [[ -z "$VERSION" ]]; then
            echo "Error: Version input is required but not provided."
            exit 1
          fi
          echo "Releasing version: $VERSION"

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install Dependencies
        run: go mod tidy

      - name: Build Code
        run: go build -v ./...

      - name: Run Malware Scan
        uses: dell/common-github-actions/malware-scanner@main
        with:
          directories: .
          options: -ri

      - name: Create New Tag
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git tag v${{ needs.compute-version.outputs.next_version }}
          git push origin v${{ needs.compute-version.outputs.next_version }}

      - name: Create Release
        id: release_notes
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.compute-version.outputs.next_version }}
          name: Release v${{ needs.compute-version.outputs.next_version }}
          draft: false
          prerelease: false
          generate_release_notes: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b release/v${{ needs.compute-version.outputs.next_version }}
          git push origin release/v${{ needs.compute-version.outputs.next_version }}

