# Copyright (c) 2024 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

# This workflow is used to release libraries like gobrick, gofsutil etc.
name: Release Go Client Libraries

# Invocable as a reusable workflow
on:
  workflow_call:
    inputs:
      version:
        description: 'Version to release (major, minor, patch), ex: 1.0.0'
        required: true
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (major, minor, patch), ex: 1.0.0'
        required: true
        default: 'none'
  repository_dispatch: # Triggered from another repo (libs)
    types: [auto-release-workflow]

jobs:
  build-and-scan:
    name: Build, Scan and Release
    runs-on: ubuntu-latest
    steps:
      - name: Set version from payload or input
        run: |
          if [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            echo "Version from payload: ${{ github.event.client_payload.version }}"
            echo "VERSION=${{ github.event.client_payload.version }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.version }}" != "none" ]]; then
            echo "Version from input: ${{ github.event.inputs.version }}"
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "Invalid version specified. Exiting."
            exit 1
          fi

      - name: Validate version input
        run: |
          if [[ "${{ env.VERSION }}" == "none" || ! "${{ env.VERSION }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version specified: ${{ env.VERSION }}. It must follow major.minor.patch format."
            exit 1
          fi

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Run malware scan
        uses: dell/common-github-actions/malware-scanner@main
        with:
          directories: .
          options: -ri

      - name: Create new tag
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}

      - name: Create Release
        id: release_notes
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          draft: true
          prerelease: false
          generate_release_notes: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b release/v${{ env.VERSION }}
          git push origin release/v${{ env.VERSION }}
