name: Dummy Test Workflow

on:
  workflow_call:
    inputs:
      gpg_key:
        description: 'GPG Key'
        required: true
        type: string

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use GPG Key
        run: |
          echo "GPG Key: ${{ inputs.gpg_key }}"
          # Add your steps that use the GPG key here

