# Copyright (c) 2024 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

# Trigger workflow for auto release of CSM projects
name: Trigger Auto Release Workflow

on:
  workflow_dispatch:

jobs:
  trigger:
    name: Trigger Auto Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo:
          [
            "meggm/test-gofsutil-release",
          ]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.repo }}

      - name: Get the latest release version from the repo
        id: get_latest_version
        run: |
          # Fetch the latest release version from the libs repository
          LATEST_VERSION=$(curl -s https://api.github.com/repos/${{ matrix.repo }}/releases/latest | jq -r .tag_name)
          echo "Latest version: $LATEST_VERSION"
          # Increment the minor version (e.g., v1.2.3 -> v1.3.0)
          VERSION_PARTS=(${LATEST_VERSION//./ })
          VERSION_PARTS[1]=$((VERSION_PARTS[1] + 1))  # Increment minor version
          NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.0"  # Set patch version to 0
          echo "New version to release: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          
      - name: Trigger Auto Release
        uses: peter-evans/repository-dispatch@v3
        with:
          # For token information, see: https://github.com/peter-evans/repository-dispatch/tree/main?tab=readme-ov-file#token
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: auto-release-workflow
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "version": "${{ env.NEW_VERSION }}"}'
