# Copyright (c) 2024 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

# This WorkFlow is used to trigger the release of csm repos using one-click action

name: Get Latest Release Version
on:
  workflow_dispatch:

jobs:
  get-release:
    runs-on: ubuntu-latest
    steps:
      - name: Define Repository Name
        id: define_repo
        run: |
          # Hardcoded repository name
          #REPO="meggm/test-gofsutil-release"
          REPO="dell/gofsutil"
          echo "repository=$REPO" >> $GITHUB_OUTPUT

      - name: Get Latest Release Version
        id: get_release
        run: |
          REPO="${{ steps.define_repo.outputs.repository }}"
          echo "Fetching latest release for $REPO"
          
          # Fetch the latest release version using GitHub API
          RELEASE_VERSION=$(curl -s "https://api.github.com/repos/$REPO/releases/latest" | jq -r '.tag_name')
          
          # Handle the case where no release is found
          if [[ "$RELEASE_VERSION" == "null" ]]; then
            echo "No release found for $REPO"
            RELEASE_VERSION="No release found"
          fi

          echo "Latest release version: $RELEASE_VERSION"
          echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: Print Latest Release Version
        run: |
          echo "The latest release version for the repository is: ${{ steps.get_release.outputs.release_version }}"
