# Copyright (c) 2024 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

# This WorkFlow is used to trigger the release of csm repos using one-click action

name: Get Latest Release Version
on:
  workflow_dispatch:
    inputs:
      repos:
        description: 'List of public GitHub repositories (comma-separated)'
        required: true

jobs:
  find-latest-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Find Latest Release Versions
        id: find-latest
        run: |
          latest_versions=()
          for repo in ${{ inputs.repos }}; do
            repo=${repo//,/ }
            url="https://api.github.com/repos/$repo/releases/latest"
            response=$(curl -s -X GET "$url")
            version=$(echo "$response" | jq -r '.tag_name')
            latest_versions+=" $repo=$version"
          done
          echo "::set-output name=latest_versions::$latest_versions"

      - name: Display Latest Versions
        run: |
          echo "Latest versions:"
          echo "${{ steps.find-latest.outputs.latest_versions }}"
          echo "##[endgroup]"

      - name: Update Version to Next Minor
        run: |
          updated_versions=()
          for repo in ${{ inputs.repos }}; do
            version=${{ steps.find-latest.outputs.latest_versions }} | grep "$repo=" | cut -d'=' -f2-
            new_version=$(echo "$version" | sed 's/^\([0-9]*\)\.([0-9]*).*/\1 \2/')
            new_version=$(echo "${new_version%% }" | awk '{print $1 + 1}' | awk '{print $0 ".0"}')
            updated_versions+=" $repo=$new_version"
            echo "Updating $repo version from $version to $new_version"
            sed -i "s/$version/$new_version/" VERSION
          done

      - name: Display Updated Versions
        run: |
          echo "Updated versions:"
          for version in $updated_versions; do
            repo=${version%%=*}
            version=${version#*=}
            echo "${repo}=${version}"
          done
          echo "##[endgroup]
