name: Versioning Workflow

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      image:
        required: true
        type: string

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Show version and image
        run: |
          echo "Version: ${{ inputs.version }}"
          echo "Image: ${{ inputs.image }}"
